Add rarity and notes + some translation fixes
EclipseTech/FishingBuddy pull request #24
Opened 2022-05-22 18:58 UTC by Quachero

2022-05-22 20:53 UTC, EclipseTech commented
Please fix the deleted file then I can merge this.

2022-05-22 20:57 UTC, EclipseTech requested changes
Thanks for translating the rest.

2022-05-22 20:57 UTC, EclipseTech commented on Properties/Strings.fr.resx
> +    <value>Poisson d\'eau douce</value>
XML says that only characters that need to be escaped are `&` and `<`

So this shouldn't need to be escaped.

2022-05-26 11:03 UTC, Quachero commented
Hi

I remove backslash.

For border_x file, I know why git want to remove it. It's a case-sensitive problem. In your ref file, you have border_x.png and border_X.png. And don't know why, but the 2 files don't want to live together in my environnement ...

![original_work](https://user-images.githubusercontent.com/19779054/170475475-32c6d796-e3bc-4671-b696-fb1b1a2d36ac.PNG)

So, border_X.png is removed on my environnement, but isn't a really a problem, border-x.png is keeped :

![my_merge_request](https://user-images.githubusercontent.com/19779054/170475603-20e4d6b4-655b-467c-a176-6c0a7044acf2.PNG)

And on your code, you use only border_x.png, so border_X.png seem useless :

![border_x_usage](https://user-images.githubusercontent.com/19779054/170475721-5b43fd16-e22a-4f41-bf78-a54e48935376.PNG)

2022-06-05 13:41 UTC, merged

2022-06-05 13:42 UTC, EclipseTech commented
Thanks, I missed this somehow. Also didn't see that there were 2 border_x and border_X